In [18]:
import numpy as np

In [106]:
points = []
n = int(input("Enter number of points"))
for i in range(n):
    x = int(input())
    y = int(input())
    z = int(input())
    temp = []
    temp.append(x)
    temp.append(y)
    temp.append(z)
    points.append(temp)
    print(points)

Enter number of points4
2
0
2
[[2, 0, 2]]
0
2
2
[[2, 0, 2], [0, 2, 2]]
-2
0
2
[[2, 0, 2], [0, 2, 2], [-2, 0, 2]]
0
-2
2
[[2, 0, 2], [0, 2, 2], [-2, 0, 2], [0, -2, 2]]


 pos_of_camera = []
 x = int(input("Enter position of camera"))
 y = int(input())
 z = int(input())

In [107]:
pos_of_camera = [] 
x = int(input("Enter position of camera"))
y = int(input())
z = int(input())
pos_of_camera.append(x)
pos_of_camera.append(y)
pos_of_camera.append(z)

Enter position of camera0
0
0


In [108]:
pos_of_plane = int(input("Enter position of projection plane"))

Enter position of projection plane1


In [109]:
pos_of_camera = np.array(pos_of_camera)
points = np.array(points)

In [110]:
#Translate to origin
# np.size(points)

In [111]:
# np.dtype(pos_of_camera)

In [112]:
# pos_of_camera.shape

In [113]:
# points.shape

In [114]:
# points.dtype

In [115]:
tr_points = points-pos_of_camera
tr_points

array([[ 2,  0,  2],
       [ 0,  2,  2],
       [-2,  0,  2],
       [ 0, -2,  2]])

In [116]:
points

array([[ 2,  0,  2],
       [ 0,  2,  2],
       [-2,  0,  2],
       [ 0, -2,  2]])

In [117]:
tr_plane = pos_of_plane - pos_of_camera[2]

In [118]:
tr_plane

1

In [119]:
print(tr_points[:,:2])
print(tr_points[:,[2]])
pr_points = (tr_points[:,:2]/tr_points[:,[2]]) * tr_plane
#Invert translation
final_points = pr_points + pos_of_camera[:2]
final_points = np.concatenate((final_points,np.ones((n,1)) * pos_of_plane), axis = 1)
print("--------------------------------------------------------------------------------")
print(final_points)

[[ 2  0]
 [ 0  2]
 [-2  0]
 [ 0 -2]]
[[2]
 [2]
 [2]
 [2]]
--------------------------------------------------------------------------------
[[ 1.  0.  1.]
 [ 0.  1.  1.]
 [-1.  0.  1.]
 [ 0. -1.  1.]]
